### ISSUE TITLE
implement channel for pulsar

### ISSUE THREAD

**Issue by subes** [invesdwin/invesdwin-context-integration#15]
https://pulsar.apache.org/

**Comment by acristea2323** [comment]
**Pulsar features**
- Rapid Horizontal Scalability: scales horizontally to handle the increased load.
- Low-latency messaging and streaming: acknowledge messages individually (RabbitMQ style) or cumulative per partition (i.e., offset-like).
- Seamless Geo-Replication: Protect against complete zone outages using replication across different geographic regions. Flexible and configurable replication strategies across distant Pulsar Clusters.
- Multi-tenancy as a first-class citizen: Maintain one cluster for your entire organization using tenants. Access control across data and actions using tenant policies. 
- Automatic Load Balancing Add or remove nodes and let Pulsar load balance topic bundles automatically. Hot spotted topic bundles are automatically split and evenly distributed across the brokers.
- Serverless Functions: Write and deploy functions natively using Pulsar Functions. Process messages using Java, Go, or Python without deploying fully-fledged applications. Kubernetes runtime is bundled.

**Pulsar structure**

![Image](https://github.com/user-attachments/assets/f0981654-051e-459e-9667-69408bb16262)

- **Producer & Consumer:** A Pulsar client contains a consumer and a producer. A producer writes messages on a topic. A consumer reads messages from a topic and acknowledges specific messages or all up to a specific message.
- **Apache Zookeeper**: Pulsar and BookKeeper use Apache ZooKeeper to save metadata coordinated between nodes, such as a list of ledgers per topic, segments per ledger, and mapping of topic bundles to a broker. It’s a cluster of highly available and replicated servers (usually 3)
-**Pulsar Brokers:** Topics (i.e., partitions) are divided among Pulsar brokers. A broker receives messages for a topic and appends them to the topic’s active virtual file (a.k.a ledger), hosted on the Bookkeeper cluster. Brokers read messages from the cache (mostly) or BookKeeper and dispatch them to the consumers. Brokers also receive message acknowledgments and persist them to the BookKeeper cluster as well. Brokers are stateless (don't use/need a disk).
- **Apache Bookkeeper**: Apache BookKeeper is a cluster of nodes called bookies. Each virtual file (a.k.a ledger) is divided into consecutive segments, and each segment is kept on 3 bookies by default (replicated by the client - i.e., the broker). Operators can add bookies rapidly since no data reshuffling (moving) between them is required. They immediately share the incoming write load.

**Differences between Pulsar and Kafka**
- Pulsar has a multi layer architecture where the broker handles the message routing and delivery. This is because the Bookkeeper is used for long term storage. This allows for more flexibility and independent scaling of both layers.
- Pulsar supports streaming and message queuing allowing features such as competing consumers and fail-over subscriptions. It allows for resource separation and access control between different teams or applications. Uses geo-replication allowing to replicate data across multiple data centres. Uses a push model where the broker pushes the messages to consumers resulting in lower latency often. Allows to offload older data to cheaper data storage solutions.
- Kafka has a monolithic architecture where the broker does the job of the bookeeper as well. This requires rebalancing of the data across the cluster when scaling Kafka which is time-consuming. Kafka is more of a great choice for high-throughput streaming applications where performance and durability are critical.

**Messaging structure and features**
- Messages carry values, payloads, where the messages contain raw bytes although it can transform to data schema. 
- Messages contain a key, which is a short name of message key or partition key. This feature can be used optionally as its useful for topic 
- Properties, optional key/value map of user-defined properties.
- Producer name automatically has a default name if it´s not specified.
-Messages are part of an ordered sequence inside their topic. A sequenceID of a message is initially assigned by its producer, indicating its order in that sequence which can also be customized. SequenceID can also be used for message deduplication, where if brokerDeduplicationEnabled is set to true, the seqID is unique to each message within a producer of a topic (non-partitioned) or in a partition.
-Messages get a messageID as soon as they´re stored by bookies. It´s unique within a pulsar cluster and indicates a specific position in a ledger.
- Messages contain a publish time of when the message is published automatically applied by the producer. An optional Event Time is attached to a message by applications for example when a message is processed. Default value is 0.
- Default max size of a message is 5MB, but this can be changed in the broker.conf file and bookkeeper.conf file. If messages are larger than the max size they´re automatically rejected.

**Acknowledgements**
- Acknowledgments are sent by a consumer after a message consumption is successful. After all subscriptions have acknowledged, the message will be permanently deleted. This is pulsar´s way of knowing if a message can be deleted.
- For batching, batch index acknowledgment can be enabled to avoid dispatching acknowledged messages to the consumer.
- Messages can be acknowledged:
    1. individually, consumer ack each message and sends ack request to the broker. Use consumer.acknowledge(msg),
    2. Cumulatively, consumer only ack the last message it received. All messages in the stream up to the provided message are not redelivered to that consumer. Use consumer.acknowledgeCumulative(msg),
- **NOTE:** cumulative ack cant be done in shared or key-shared subscription types as multiple consumers having access to the same subscription. Individual ack should be used then.
- The acknowledgment timeout mechanism allows to set a time range during which the client tracks the unacknowledged messages. After this acknowledgment timeout (ackTimeout) period, the client sends redeliver unacknowledged messages request to the broker, which then the broker re sends the unacknowledged messages to the consumer. The acknowledgment timeout mechanism can be configured to redeliver the message if it is not acknowledged after ackTimeout or to execute a timer task to check the acknowledgment timeout messages during every ackTimeoutTickTime period.
- The message redelivery behavior should be as follows:
<!DOCTYPE html>
<html>
<head>
</head>
<body lang="en-US" link="#000080" vlink="#800000" dir="ltr">
<dl><dd>
	
Redelivery count | Redelivery delay
-- | --
1 | 10 + 1 seconds
2 | 10 + 2 seconds
3 | 10 + 4 seconds
4 | 10 + 8 seconds
5 | 10 + 16 seconds
6 | 10 + 32 seconds
7 | 10 + 60 seconds
8 | 10 + 60 seconds


</dd></dl>
</body>
</html>


**Negative acknowledgment**
The negative acknowledgment mechanism allows you to send a notification to the broker indicating the consumer did not process a message. When a consumer fails to consume a message and needs to re-consume it, the consumer sends a negative acknowledgment (nack) to the broker, triggering the broker to redeliver this message to the consumer.
- Messages are negatively acknowledged individually or cumulatively, depending on the consumption subscription type.
- In Exclusive and Failover subscription types, consumers only negatively acknowledge the last message they receive.
- In Shared and Key-Shared subscription types, consumers can negatively acknowledge messages individually.
Negative acknowledgments on ordered subscription types, such as Exclusive, Failover and Key-Shared, might cause failed messages being sent to consumers out of the original order. It needs to be made sure that the message is negatively acknowledged before the acknowledgment timeout.

The message redelivery behavior should be as follows:
<!DOCTYPE html>
<html>
<head>
</head>
<body lang="en-US" link="#000080" vlink="#800000" dir="ltr">

Redelivery count | Redelivery delay
-- | --
1 | 1 seconds
2 | 2 seconds
3 | 4 seconds
4 | 8 seconds
5 | 16 seconds
6 | 32 seconds
7 | 60 seconds
8 | 60 seconds


</body>
</html>
 
 
 
**Retry letter topic**

![Image](https://github.com/user-attachments/assets/efa415b2-387b-4aa3-996c-617a9ea5fe0a)

- Stores messages that failed to be consumed and retry to consume them later. The interval can be customized to to which the messages are redelivered. 
- Retry letter topic serves failure handling through message re delivery to ensure critical data is not lost, while delayed message delivery is intended to deliver a message with a specified time delay.


**Dead letter topic**
- Dead letter topic allows to continue message consumption even when some messages are not consumed successfully. 
- Messages that have failed to be consumed are stored in a specific topic, which is called the dead letter topic. The functionality of a dead letter topic is implemented by consumers. You can decide how to handle the messages in the dead letter topic.
- By default, there is no subscription during DLQ topic creation. Without a just-in-time subscription to the DLQ topic, messages may be lost. To automatically create an initial subscription for the DLQ, specify the initialSubscriptionName parameter. If this parameter is set but the broker's allowAutoSubscriptionCreation is disabled, the DLQ producer will fail to be created.
- Dead letter topic serves message redelivery, which is triggered by acknowledgment timeout or negative acknowledgment or retry letter topic.
      
**Compression**
- Pulsar client supports the following compression types:
       1. LZ4
       2. ZLIB
       3. ZSTD
       4. SNAPPY- Compression types are stored in the message metadata, so consumers can adopt different compression types automatically, as needed

**Batching**
- When batching is enabled, the producer accumulates and sends a batch of messages in a single request. The batch size is defined by the maximum number of messages and the maximum publish latency. Therefore, the backlog size represents the total number of batches instead of the total number of messages.
- Batches are tracked and stored as single units rather than as individual messages. Consumers unbundle a batch into individual messages. However, scheduled messages (configured through the deliverAt or the deliverAfter parameter) are always sent as individual messages even when batching is enabled.
- A batch is acknowledged when all of its messages are acknowledged by a consumer. It means that when not all batch messages are acknowledged, then unexpected failures, negative acknowledgments, or acknowledgment timeouts can result in a redelivery of all messages in this batch. But this doesn’t happen when batch index acknowledgment is enabled as this is sent to the broker to then only send the messages in the batch that weren’t acknowledged.
- You can enable batch index acknowledgment by setting the acknowledgmentAtBatchIndexLevelEnabled parameter to true at the broker side. Enabling batch index acknowledgment results in more memory overheads. Batch index acknowledgment must also be enabled in the consumer by calling .enableBatchIndexAcknowledgment(true);
- **NOTE**: When using the synchronous send method for producing messages, the batch will be sent immediately even if it is not full. This helps reduce message sending latency and prevents blocking of the caller's thread. When producing messages in a single thread, you should use the asynchronous sendAsync method to send messages in batches.
      
**Chunking**
- Message chunking enables Pulsar to process large payload messages by splitting the message into chunks at the producer side and aggregating chunked messages at the consumer side.
- With message chunking enabled, when the size of a message exceeds the allowed maximum payload size (the maxMessageSize parameter of broker), the workflow of messaging is as follows:
    1. The producer splits the original message into chunked messages and publishes them with chunked metadata to the broker separately and in order. 
    2. The broker stores the chunked messages in one managed ledger in the same way as that of ordinary messages, and it uses the chunkedMessageRate parameter to record chunked message rate on the topic. 
    3. The consumer buffers the chunked messages and aggregates them into the receiver queue when it receives all the chunks of a message. 
    4. The client consumes the aggregated message from the receiver queue.
- **NOTE**: Chunking is only available for persistent topics and cannot be enabled simultaneously with batching. Before enabling chunking, batching needs to be disabled. 

**Topics**
<!DOCTYPE html>
<html>
<head>
</head>
<body lang="en-US" link="#000080" vlink="#800000" dir="ltr">

Topic name component | Description
-- | --
persistent 				/ non-persistent | This identifies the type of 				topic. Pulsar supports two kind of topics: persistent 				and non-persistent. 				The default is persistent, so if you do not specify a type, the 				topic is persistent. With persistent topics, all messages are 				durably persisted on disks (if the broker is not standalone, 				messages are durably persisted on multiple disks), whereas data 				for non-persistent topics is not persisted to storage disks.
tenant | The topic tenant within the 				instance. Tenants are essential to multi-tenancy in Pulsar, and 				spread across clusters.
namespace | The administrative unit of 				the topic, which acts as a grouping mechanism for related topics. 				Most topic configuration is performed at the namespace level. 				Each tenant has one or more namespaces.
topic | The final part of the name. 				Topic names have no special meaning in a Pulsar instance.


</body>
</html>

**Subscriptions**

![Image](https://github.com/user-attachments/assets/e0b52de6-e667-4d94-9b23-3b323e3c50f2)

- **Exclusive**: The exclusive type is a subscription type that only allows a single consumer to attach to the subscription. If multiple consumers subscribe to a topic using the same subscription, an error occurs. Note that if the topic is partitioned, all partitions will be consumed by the single consumer allowed to be connected to the subscription.
- **Failover**: The failover type is a subscription type that multiple consumers can attach to the same subscription. A master consumer is picked for a non-partitioned topic or each partition of a partitioned topic and receives messages. When the master consumer disconnects, all (non-acknowledged and subsequent) messages are delivered to the next consumer in line. If there is one non-partitioned topic. The broker picks consumers in the order they subscribe to non-partitioned topics.
- **Shared**: The shared subscription type in Pulsar allows multiple consumers to attach to the same subscription. Messages are delivered in a round-robin distribution across consumers, and any given message is delivered to only one consumer. When a consumer disconnects, all the messages that were sent to it and not acknowledged will be rescheduled for sending to the remaining consumers.
- **Key-Shared**: The Key-Shared subscription type in Pulsar allows multiple consumers to attach to the same subscription. But different with the Shared type, messages in the Key-Shared type are delivered in distribution across consumers and messages with the same key or same ordering key are delivered to only one consumer. No matter how many times the message is re-delivered, it is delivered to the same consumer

<!DOCTYPE html>
<html>
<head>
</head>
<body lang="en-US" link="#000080" vlink="#800000" dir="ltr">

Subscription mode | Description | Note
-- | -- | --
Durable | The cursor is durable, which 				retains messages and persists the current position.  If a 				broker restarts from a failure, it can recover the cursor from 				the persistent storage (BookKeeper), so that messages can 				continue to be consumed from the last consumed position. | Durable 				is the default 				subscription mode.
NonDurable | The cursor is non-durable. 				 Once a broker stops, the cursor is lost and can never be 				recovered, so that messages can 				not continue 				to be consumed from the last consumed position. | Reader's subscription mode 				is NonDurable 				in nature and it does not prevent data in a topic from being 				deleted. Reader's subscription mode can 				not be 				changed.


</body>
</html>

**Routing modes**
- When publishing to partitioned topics, you must specify a routing mode. The routing mode determines each message should be published to which partition or which internal topic.
- There are three MessageRoutingMode available:
<!DOCTYPE html>
<html>
<head>
</head>
<body lang="en-US" link="#000080" vlink="#800000" dir="ltr">

Mode | Description
-- | --
RoundRobinPartition | If no key is provided, the 				producer will publish messages across all partitions in 				round-robin fashion to achieve maximum throughput. Please note 				that round-robin is not done per individual message but rather 				it's set to the same boundary of batching delay, to ensure 				batching is effective. While if a key is specified on the 				message, the partitioned producer will hash the key and assign 				message to a particular partition. This is the default mode.
SinglePartition | If no key is provided, the 				producer will randomly pick one single partition and publish all 				the messages into that partition. While if a key is specified on 				the message, the partitioned producer will hash the key and 				assign message to a particular partition.
CustomPartition | Use custom message router 				implementation that will be called to determine the partition for 				a particular message. User can create a custom routing mode by 				using the Java client 				and implementing the 				MessageRouter 				interface.


</body>
</html>

Information taken from https://pulsar.apache.org/docs/4.0.x/concepts-messaging/

**Comment by acristea2323** [comment]
**Tasks in relation to the features to test**

- [ ] download and unpack pulsar
- [ ] test a standalone pulsar instance using terminal to see how everything is working
- [ ] set up the java project with the appropriate maven project
- [ ] try messaging on terminal by creating a new consumer and producer with a topic
- [ ] do the same process on eclipse by sending one message and checking for assertion and checking sequence number matches 1
- [ ] increase size until valuable results can be recorded.
- [ ] change the setup so that is uses docker
- [ ] add latency and throughput measurement sections to create a test setup
- [ ] test persistent and non-persistent topic
- [ ] test batching with different sizes 
- [ ] test synchronous and asynchronous sending
- [ ] configure the size of the consumer queue
- [ ] test compression methods
- [ ] change the JVM heap size and the Broker's cache for tuning
- [ ] test the best version of pulsar for a latency and throughput test 
- [ ] test pulsar with JForex data.

**Comment by subes** [comment]
It is possible to create plugins for kafka brokers in order to directly handle messages at the broker side (sort of colocation). We could maybe even embed brokers and create a network of brokers for peer to peer connections. Though this would require more investigation and we don't have a use-case for this currently (except if we wanted to embed a pulsar broker into our data microservice): https://pulsar.apache.org/docs/next/develop-plugin/

Pulsar also offers serverless computing based on messages as a light-weight alternative to [Apache Storm](http://storm.apache.org/), [Apache Heron](https://heron.incubator.apache.org/), or [Apache Flink](https://flink.apache.org/): https://pulsar.apache.org/docs/4.0.x/functions-overview/
